#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
img2c.py - 把图片转成 STM32 LCD RGB565 C 数组

用法:
    python img2c.py <输入图片> <输出.h> [数组名] [高]

说明:
    - 目标屏幕 240 宽 x [高] (默认 320), RGB565 16bit
    - 图片按原比例缩放并居中, 剩余区域用黑色填充 (letterbox)
    - 生成 const uint16_t NAME[240*高] = {...}; 存入 Flash
    - 高取 320 时满屏 150KB; 受 Bootloader 分区限制可调小 (如 280=131KB)

嵌入后调用:
    LCD_ShowImage(x, y, 240, H, NAME);   /* y 居中: (320-H)/2 */
"""
import sys
from PIL import Image

W = 240
H = int(sys.argv[4]) if len(sys.argv) > 4 else 320


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    src = sys.argv[1]
    dst = sys.argv[2]
    name = sys.argv[3] if len(sys.argv) > 3 else "test_image"

    img = Image.open(src).convert("RGB")

    # 按比例缩放并居中 (letterbox)
    iw, ih = img.size
    scale = min(W / iw, H / ih)
    nw, nh = int(iw * scale), int(ih * scale)
    img = img.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGB", (W, H), (0, 0, 0))
    canvas.paste(img, ((W - nw) // 2, (H - nh) // 2))
    img = canvas

    px = img.load()
    rows = []
    for y in range(H):
        vals = []
        for x in range(W):
            r, g, b = px[x, y]
            vals.append("0x%04X" % rgb565(r, g, b))
        rows.append(", ".join(vals))

    out = (
        "/* Generated by img2c.py from %s */\n"
        "const uint16_t %s[%d] = {\n" % (src, name, W * H)
    )
    for i in range(0, H, 4):
        out += "    " + ",\n    ".join(rows[i:i + 4]) + ",\n"
    out += "};\n"

    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    print("OK: %s  (%d pixels, %.1f KB)" % (dst, W * H, W * H * 2 / 1024.0))


if __name__ == "__main__":
    main()
